import type { Lang } from './lang.ts';
const en = {
  features: 'Surface anatomy', show: 'Show surface features', hide: 'Hide surface features',
  note: 'Schematic teaching relief and fitted landmarks; patterns vary between teeth and people. Draft pending dental review.',
  mesial: 'Mesial surface', distal: 'Distal surface', occlusal: 'Biting surface', inner: 'Inner surface', facial: 'Facial surface',
  vessels: 'Vessels', arteries: 'Arteries', veins: 'Veins', both: 'Arteries & veins', allSides: 'Both sides', right: 'Right', left: 'Left',
  vesselView: 'Inspect vessel course', vesselHint: 'Follow red arteries and blue veins through translucent bone and muscle. Choose a side or select a vessel for its relationships.',
  sinuses: 'Sinuses', sinusView: 'Inspect all sinuses', sinusHint: 'Air spaces are shown as translucent volumes. Frontal, sphenoidal and ethmoidal geometry is schematic; air-cell number and sinus size vary.',
};
type Text = { [K in keyof typeof en]: string };
export const STUDY_TEXT: Record<Lang, Text> = {
  en,
  sv: { mesial: 'Mesialyta', distal: 'Distalyta', features: 'Ytanatomi', show: 'Visa ytstrukturer', hide: 'Dölj ytstrukturer', note: 'Schematisk undervisningsrelief och anpassade markörer; mönster varierar mellan tänder och individer. Utkast i väntan på tandläkargranskning.', occlusal: 'Tuggyta', inner: 'Insida', facial: 'Utsida', vessels: 'Blodkärl', arteries: 'Artärer', veins: 'Vener', both: 'Artärer & vener', allSides: 'Båda sidor', right: 'Höger', left: 'Vänster', vesselView: 'Utforska kärlets förlopp', vesselHint: 'Följ röda artärer och blå vener genom genomskinligt ben och muskler. Välj sida eller kärl för att se anatomiska samband.', sinuses: 'Bihålor', sinusView: 'Utforska alla bihålor', sinusHint: 'Luftrum visas som genomskinliga volymer. Pannbihålor, kilbensbihålor och silbensceller är schematiska; cellantal och storlek varierar.' },
  de: { mesial: 'Mesialfläche', distal: 'Distalfläche', features: 'Oberflächenanatomie', show: 'Oberflächenmerkmale zeigen', hide: 'Oberflächenmerkmale ausblenden', note: 'Schematisches Lehrrelief und angepasste Landmarken; Muster variieren zwischen Zähnen und Personen. Entwurf bis zur zahnärztlichen Prüfung.', occlusal: 'Kaufläche', inner: 'Innenseite', facial: 'Außenseite', vessels: 'Gefäße', arteries: 'Arterien', veins: 'Venen', both: 'Arterien & Venen', allSides: 'Beide Seiten', right: 'Rechts', left: 'Links', vesselView: 'Gefäßverlauf untersuchen', vesselHint: 'Rote Arterien und blaue Venen durch transparenten Knochen und Muskeln verfolgen. Eine Seite oder ein Gefäß für seine Beziehungen wählen.', sinuses: 'Nebenhöhlen', sinusView: 'Alle Nebenhöhlen untersuchen', sinusHint: 'Lufträume erscheinen als transparente Volumen. Stirn-, Keilbeinhöhlen und Siebbeinzellen sind schematisch; Zellzahl und Größe variieren.' },
  es: { mesial: 'Cara mesial', distal: 'Cara distal', features: 'Anatomía superficial', show: 'Mostrar detalles superficiales', hide: 'Ocultar detalles superficiales', note: 'Relieve didáctico esquemático e hitos adaptados; los patrones varían entre dientes y personas. Borrador pendiente de revisión odontológica.', occlusal: 'Superficie masticatoria', inner: 'Cara interna', facial: 'Cara externa', vessels: 'Vasos', arteries: 'Arterias', veins: 'Venas', both: 'Arterias y venas', allSides: 'Ambos lados', right: 'Derecho', left: 'Izquierdo', vesselView: 'Examinar trayecto vascular', vesselHint: 'Sigue arterias rojas y venas azules a través de huesos y músculos transparentes. Elige un lado o vaso para ver sus relaciones.', sinuses: 'Senos', sinusView: 'Examinar todos los senos', sinusHint: 'Los espacios aéreos se muestran como volúmenes transparentes. Senos frontales, esfenoidales y celdillas etmoidales son esquemáticos; su número y tamaño varían.' },
  la: { mesial: 'Superficies mesialis', distal: 'Superficies distalis', features: 'Anatomia superficiei', show: 'Structuras superficiei ostende', hide: 'Structuras superficiei cela', note: 'Reliefum didacticum schematicum et puncta adaptata; formae inter dentes et homines variant. Textus provisorius recognitionem odontologicam exspectat.', occlusal: 'Superficies masticatoria', inner: 'Superficies interna', facial: 'Superficies externa', vessels: 'Vasa sanguinea', arteries: 'Arteriae', veins: 'Venae', both: 'Arteriae et venae', allSides: 'Utrumque latus', right: 'Dextrum', left: 'Sinistrum', vesselView: 'Decursum vasis explora', vesselHint: 'Arterias rubras et venas caeruleas per ossa et musculos translucidos sequere. Latus vel vas ad relationes anatomicas elige.', sinuses: 'Sinus paranasales', sinusView: 'Omnes sinus explora', sinusHint: 'Spatia aeria ut volumina translucida ostenduntur. Sinus frontales, sphenoidales et cellulae ethmoidales schematice finguntur; numerus et magnitudo variant.' },
};
