import type { Names } from '../i18n/anatomy.ts';
import type { Lang } from '../i18n/lang.ts';
export const PARANASAL_NAMES: Record<string, Omit<Names, 'en'>> = {
  'paranasal-sinuses': { sv: 'Bihålor', de: 'Nasennebenhöhlen', es: 'Senos paranasales', la: 'Sinus paranasales' },
  'frontal-sinus': { sv: 'Pannbihåla', de: 'Stirnhöhle', es: 'Seno frontal', la: 'Sinus frontalis' },
  'sphenoidal-sinus': { sv: 'Kilbensbihåla', de: 'Keilbeinhöhle', es: 'Seno esfenoidal', la: 'Sinus sphenoidalis' },
  'ethmoidal-air-cells': { sv: 'Silbensceller', de: 'Siebbeinzellen', es: 'Celdillas etmoidales', la: 'Cellulae ethmoidales' },
};
const summaries: Record<string, Record<Lang, string>> = {
  'paranasal-sinuses': {
    en: 'The maxillary, frontal and sphenoidal sinuses and ethmoidal air cells are air spaces surrounding the nasal cavity. Their mucosal lining participates in mucus clearance; their broader functions remain debated. Explore each group in relation to the jaws, orbit and skull base. These teaching volumes do not show drainage pathways or individual variation.',
    sv: 'Käkbihålor, pannbihålor, kilbensbihålor och silbensceller är luftrum runt näshålan. Slemhinnan deltar i slemtransport; deras övriga funktioner är omdiskuterade. Utforska gruppernas relation till käkar, ögonhålor och skallbas. Undervisningsvolymerna visar inte dränagevägar eller individuell variation.',
    de: 'Kiefer-, Stirn-, Keilbeinhöhlen und Siebbeinzellen sind Lufträume um die Nasenhöhle. Ihre Schleimhaut dient dem Schleimtransport; weitere Funktionen sind umstritten. Die Gruppen stehen in Beziehung zu Kiefern, Augenhöhlen und Schädelbasis. Diese Lehrvolumen zeigen weder Abflusswege noch individuelle Varianten.',
    es: 'Los senos maxilares, frontales y esfenoidales y las celdillas etmoidales son espacios aéreos alrededor de la cavidad nasal. Su mucosa participa en la eliminación del moco; sus otras funciones siguen en debate. Se relacionan con los maxilares, las órbitas y la base craneal. Estos volúmenes didácticos no muestran vías de drenaje ni variación individual.',
    la: 'Sinus maxillares, frontales, sphenoidales et cellulae ethmoidales spatia aeria circa cavitatem nasi sunt. Tunica mucosa ad mucum transportandum pertinet; aliae functiones disputantur. Relationes ad maxillas, orbitas et basim cranii explorantur. Volumina didactica vias effluxus et variationes individuales non exhibent.',
  },
  'frontal-sinus': {
    en: 'An air space in the frontal bone above the orbit, anterior to the anterior cranial fossa. The right and left spaces are separated by a variable septum and may differ greatly in size or be absent. Mucus drains through the frontal recess toward the middle nasal meatus. The displayed cavity is a schematic regional example; its recess and ostium are not modeled.',
    sv: 'Ett luftrum i pannbenet ovanför ögonhålan, framför främre skallgropen. Höger och vänster hålrum skiljs av ett varierande septum och kan vara olika stora eller saknas. Slem dräneras via frontalrecessen mot mellersta näsgången. Den visade håligheten är ett schematiskt regionalt exempel; recess och ostium är inte modellerade.',
    de: 'Ein Luftraum im Stirnbein über der Augenhöhle und vor der vorderen Schädelgrube. Eine variable Scheidewand trennt die rechte und linke Höhle; Größe und Vorhandensein variieren. Schleim fließt über den Recessus frontalis zum mittleren Nasengang. Die gezeigte Höhle ist ein schematisches regionales Beispiel ohne Recessus oder Ostium.',
    es: 'Espacio aéreo del hueso frontal sobre la órbita, anterior a la fosa craneal anterior. Un tabique variable separa las cavidades derecha e izquierda; pueden tener tamaños distintos o estar ausentes. El moco drena por el receso frontal hacia el meato nasal medio. La cavidad mostrada es un ejemplo regional esquemático sin receso ni ostium modelados.',
    la: 'Spatium aerium in osse frontali supra orbitam, ante fossam cranii anteriorem. Septum variabile cavitates dextram et sinistram separat; magnitudo et praesentia variant. Mucus per recessum frontalem ad meatum nasi medium defluit. Cavitas ostensa exemplum regionale schematicum est; recessus et ostium non finguntur.',
  },
  'sphenoidal-sinus': {
    en: 'An air space in the body of the sphenoid, posterior to the nasal cavity and ethmoidal cells, below the sellar region. Its walls are close to the optic nerves and internal carotid arteries. It opens into the sphenoethmoidal recess. The two displayed spaces are schematic; septation, pneumatization and these unmodeled neurovascular relationships vary and cannot be assessed from this model.',
    sv: 'Ett luftrum i kilbenets kropp, bakom näshålan och silbenscellerna, nedanför sellaregionen. Väggarna ligger nära synnerver och inre karotisartärer. Det mynnar i den sfenoetmoidala recessen. De två visade rummen är schematiska; septa, pneumatisering och dessa ej modellerade neurovaskulära relationer varierar och kan inte bedömas i modellen.',
    de: 'Ein Luftraum im Keilbeinkörper hinter Nasenhöhle und Siebbeinzellen, unter der Sellaregion. Seine Wände liegen nahe den Sehnerven und inneren Halsschlagadern. Er mündet in den Recessus sphenoethmoidalis. Die beiden gezeigten Räume sind schematisch; Septen, Pneumatisation und diese nicht modellierten neurovaskulären Beziehungen variieren und lassen sich hier nicht beurteilen.',
    es: 'Espacio aéreo del cuerpo del esfenoides, posterior a la cavidad nasal y celdillas etmoidales, bajo la región selar. Sus paredes están próximas a los nervios ópticos y arterias carótidas internas. Se abre al receso esfenoetmoidal. Los dos espacios son esquemáticos; tabiques, neumatización y estas relaciones neurovasculares no modeladas varían y no pueden evaluarse aquí.',
    la: 'Spatium aerium in corpore ossis sphenoidalis, post cavitatem nasi et cellulas ethmoidales, infra regionem sellarem. Parietes nervis opticis et arteriis carotidibus internis proximi sunt. In recessum sphenoethmoidalem aperitur. Spatia ostensa schematica sunt; septa, pneumatisatio et relationes neurovasculares hic non fictae variant neque ex hoc exemplo aestimantur.',
  },
  'ethmoidal-air-cells': {
    en: 'Multiple small air spaces in the ethmoidal labyrinth between the nasal cavity and orbit, beneath the anterior skull base and in front of the sphenoidal sinus. Thin bony partitions separate the cells; the lateral orbital wall is the lamina papyracea. Anterior and middle cells drain toward the middle meatus and posterior cells toward the superior meatus. Each side is represented by a selectable cluster of separate schematic cavities; the displayed count and arrangement are illustrative.',
    sv: 'Flera små luftrum i silbenslabyrinten mellan näshåla och ögonhåla, under främre skallbasen och framför kilbensbihålan. Tunna benväggar skiljer cellerna; den laterala väggen mot ögonhålan är lamina papyracea. Främre och mellersta celler dräneras mot mellersta näsgången och bakre mot övre näsgången. Varje sida visas som en valbar grupp av separata schematiska hålrum; antal och placering är illustrativa.',
    de: 'Mehrere kleine Lufträume im Siebbeinlabyrinth zwischen Nasenhöhle und Augenhöhle, unter der vorderen Schädelbasis und vor der Keilbeinhöhle. Dünne Knochenwände trennen die Zellen; lateral liegt die Lamina papyracea zur Orbita. Vordere und mittlere Zellen drainieren zum mittleren, hintere zum oberen Nasengang. Jede Seite ist eine wählbare Gruppe getrennter schematischer Höhlen; Anzahl und Anordnung sind illustrativ.',
    es: 'Pequeños espacios aéreos del laberinto etmoidal entre cavidad nasal y órbita, bajo la base craneal anterior y delante del seno esfenoidal. Tabiques óseos finos separan las celdillas; lateralmente la lámina papirácea limita con la órbita. Las anteriores y medias drenan hacia el meato medio y las posteriores hacia el superior. Cada lado es un grupo seleccionable de cavidades esquemáticas separadas; número y disposición son ilustrativos.',
    la: 'Spatia aeria parva in labyrintho ethmoidali inter cavitatem nasi et orbitam, infra basim cranii anteriorem et ante sinum sphenoidalem. Septa ossea tenuia cellulas separant; lateraliter lamina papyracea orbitam finit. Cellulae anteriores et mediae ad meatum medium, posteriores ad meatum superiorem defluunt. Utrumque latus grex cavitatum schematicarum separatarum est; numerus et dispositio illustrantur.',
  },
};
export function paranasalContent(lang: Lang) {
  return Object.fromEntries(Object.entries(summaries).map(([key, summary]) => [key, { summary: summary[lang], sources: [{ title: 'StatPearls: Nose Paranasal Sinuses', url: 'https://www.ncbi.nlm.nih.gov/sites/books/NBK499826/' }], related: key === 'paranasal-sinuses' ? ['maxillary-sinus', 'frontal-sinus', 'sphenoidal-sinus', 'ethmoidal-air-cells'] : ['paranasal-sinuses', key === 'frontal-sinus' ? 'frontal-bone' : key === 'sphenoidal-sinus' ? 'sphenoid-bone' : 'ethmoid-bone'] }]));
}
