import { LANGS, type Lang } from '../i18n/lang.ts';
import type { Names } from '../i18n/anatomy.ts';

type Translation = [string, string, string, string, string];
const definitions: Record<string, { names: Translation; description: Translation }> = {};
function define(key: string, names: Translation, description: Translation) { definitions[key] = { names, description }; }

const cusp = [
  'A raised part of the biting surface. Its slopes meet neighboring grooves and ridges and contribute to crushing food.',
  'En upphöjning på tuggytan. Dess sluttningar möter närliggande fåror och åsar och bidrar till att krossa föda.',
  'Eine Erhebung auf der Kaufläche. Ihre Abhänge grenzen an Furchen und Leisten und tragen zum Zerkleinern der Nahrung bei.',
  'Una elevación de la superficie masticatoria. Sus vertientes limitan con surcos y crestas y ayudan a triturar alimentos.',
  'Eminentia superficiei masticatoriae. Declivia eius sulcis et cristis vicinis adiacent et cibum comminuere adiuvant.',
] as Translation;
const cuspPositions: [string, Translation, Translation][] = [
  ['buccal-cusp', ['Buccal cusp', 'Buckal kusp', 'Bukkaler Höcker', 'Cúspide vestibular', 'Cuspis buccalis'], ['On the cheek-facing side of a premolar crown.', 'På premolarkronans sida mot kinden.', 'Auf der wangenseitigen Fläche einer Prämolarenkrone.', 'En el lado de la corona premolar orientado hacia la mejilla.', 'In latere coronae premolaris buccam spectante.']],
  ['lingual-cusp', ['Lingual / palatal cusp', 'Lingual / palatinal kusp', 'Lingualer / palatinaler Höcker', 'Cúspide lingual / palatina', 'Cuspis lingualis / palatina'], ['On the inner side of a premolar crown, opposite the buccal cusp; its relative size varies by tooth.', 'På premolarkronans insida, mittemot den buckala kuspen; storleken varierar mellan tänder.', 'Auf der Innenseite der Prämolarenkrone gegenüber dem bukkalen Höcker; die relative Größe variiert.', 'En la cara interna de la corona premolar, frente a la cúspide vestibular; su tamaño relativo varía.', 'In latere interno coronae premolaris cuspidi buccali opposita; magnitudo relativa variat.']],
  ['mesiobuccal-cusp', ['Mesiobuccal cusp', 'Mesiobuckal kusp', 'Mesiobukkaler Höcker', 'Cúspide mesiovestibular', 'Cuspis mesiobuccalis'], ['On the mesial, cheek-facing corner of a molar crown, closer to the dental midline than the distobuccal cusp.', 'Vid molarkronans mesiala hörn mot kinden, närmare tandbågens mittlinje än den distobuckala kuspen.', 'An der mesialen wangenseitigen Ecke der Molarenkrone, näher an der Mittellinie als der distobukkale Höcker.', 'En la esquina mesial vestibular de la corona molar, más cerca de la línea media que la cúspide distovestibular.', 'In angulo mesiobuccali coronae molaris, lineae medianae propius quam cuspis distobuccalis.']],
  ['distobuccal-cusp', ['Distobuccal cusp', 'Distobuckal kusp', 'Distobukkaler Höcker', 'Cúspide distovestibular', 'Cuspis distobuccalis'], ['On the distal, cheek-facing corner of a molar crown, behind the mesiobuccal cusp along the arch.', 'Vid molarkronans distala hörn mot kinden, bakom den mesiobuckala kuspen längs tandbågen.', 'An der distalen wangenseitigen Ecke der Molarenkrone hinter dem mesiobukkalen Höcker.', 'En la esquina distal vestibular de la corona molar, detrás de la cúspide mesiovestibular.', 'In angulo distobuccali coronae molaris, post cuspidem mesiobuccalem secundum arcum dentalem.']],
  ['mesiolingual-cusp', ['Mesiolingual / mesiopalatal cusp', 'Mesiolingual / mesiopalatinal kusp', 'Mesiolingualer / mesiopalatinaler Höcker', 'Cúspide mesiolingual / mesiopalatina', 'Cuspis mesiolingualis / mesiopalatina'], ['On the mesial inner corner of a molar crown. On upper molars, its distal ridge contributes to the oblique ridge.', 'Vid molarkronans mesiala inre hörn. På överkäksmolarer bidrar dess distala ås till den sneda åsen.', 'An der mesialen inneren Ecke der Molarenkrone. Bei oberen Molaren bildet ihre distale Leiste einen Teil der schrägen Leiste.', 'En la esquina interna mesial de la corona molar. En molares superiores su cresta distal contribuye a la cresta oblicua.', 'In angulo interno mesiali coronae molaris. In molaribus superioribus crista distalis eius ad cristam obliquam pertinet.']],
  ['distolingual-cusp', ['Distolingual / distopalatal cusp', 'Distolingual / distopalatinal kusp', 'Distolingualer / distopalatinaler Höcker', 'Cúspide distolingual / distopalatina', 'Cuspis distolingualis / distopalatina'], ['On the distal inner corner of a molar crown; its development is variable, especially on upper second and third molars.', 'Vid molarkronans distala inre hörn; utvecklingen varierar, särskilt på överkäkens andra och tredje molarer.', 'An der distalen inneren Ecke der Molarenkrone; ihre Ausprägung variiert besonders an oberen zweiten und dritten Molaren.', 'En la esquina interna distal de la corona molar; su desarrollo varía, sobre todo en segundos y terceros molares superiores.', 'In angulo interno distali coronae molaris; forma praesertim in molaribus superioribus secundis et tertiis variat.']],
  ['distal-cusp', ['Distal cusp', 'Distal kusp', 'Distaler Höcker', 'Cúspide distal', 'Cuspis distalis'], ['At the distal end of the mandibular first molar crown, forming the fifth cusp in this teaching pattern.', 'Vid den första underkäksmolarens distala kronände; den femte kuspen i detta undervisningsexempel.', 'Am distalen Ende der unteren ersten Molarenkrone; der fünfte Höcker dieses Lehrbeispiels.', 'En el extremo distal del primer molar inferior; la quinta cúspide de este ejemplo didáctico.', 'In extremo distali coronae molaris primi inferioris; quinta cuspis huius exempli didactici.']],
];
for (const [key, names, position] of cuspPositions) define(key, names, position.map((p, i) => `${p} ${cusp[i]}`) as Translation);

define('cusp-tip', ['Cusp tip', 'Kuspspets', 'Höckerspitze', 'Vértice cuspídeo', 'Apex cuspidis'], ['The summit of a canine crown where the mesial and distal cusp slopes meet. The lingual ridge extends from this region towards the cingulum.', 'Hörntandskronans spets där mesial och distal kuspsluttning möts. Den linguala åsen löper härifrån mot cingulum.', 'Die Spitze der Eckzahnkrone, an der mesialer und distaler Höckerabhang zusammentreffen. Von hier zieht die linguale Leiste zum Cingulum.', 'La cima de la corona canina donde se unen las vertientes mesial y distal. La cresta lingual se dirige desde aquí al cíngulo.', 'Summum coronae canini ubi declivia mesiale et distale conveniunt. Crista lingualis hinc ad cingulum tendit.']);
define('incisal-edge', ['Incisal edge', 'Incisalkant', 'Schneidekante', 'Borde incisal', 'Margo incisalis'], ['The cutting edge of an incisor crown, between its mesial and distal angles. Wear and age change its outline; this is a representative adult form.', 'Incisivkronans skärande kant mellan mesial och distal vinkel. Slitage och ålder ändrar formen; detta visar en representativ vuxenform.', 'Die Schneidekante der Inzisivenkrone zwischen mesialem und distalem Winkel. Alter und Abrieb verändern ihre Form; dargestellt ist ein erwachsenes Beispiel.', 'El borde cortante del incisivo entre sus ángulos mesial y distal. La edad y el desgaste modifican su contorno; se muestra una forma adulta representativa.', 'Margo secans coronae incisivi inter angulos mesialem et distalem. Aetas et attritio formam mutant; forma adulta exemplaris ostenditur.']);
define('cingulum', ['Cingulum', 'Cingulum', 'Cingulum', 'Cíngulo', 'Cingulum'], ['A convex prominence in the cervical third of the inner crown surface of anterior teeth. It borders the lingual fossa or fossae and is typically more prominent on upper anterior teeth.', 'En välvd upphöjning i den cervikala tredjedelen av framtändernas och hörntändernas inre kronyta. Den gränsar till linguala fossan eller fossorna och är ofta tydligare i överkäken.', 'Eine Wölbung im zervikalen Drittel der inneren Kronenfläche der Frontzähne. Sie begrenzt die linguale Fossa beziehungsweise Fossae und ist meist im Oberkiefer deutlicher.', 'Una prominencia convexa en el tercio cervical de la cara interna de los dientes anteriores. Limita con la fosa o fosas linguales y suele ser más marcada en los superiores.', 'Eminentia convexa in tertia cervicali superficiei internae coronae dentium anteriorum. Fossae vel fossis lingualibus adiacet et in superioribus plerumque eminentior est.']);
define('lingual-ridge', ['Lingual ridge', 'Lingual ås', 'Linguale Leiste', 'Cresta lingual', 'Crista lingualis'], ['A ridge running along the inner canine crown from the cusp tip to the cingulum, separating the mesial and distal lingual fossae. It is less pronounced on many lower canines.', 'En ås på hörntandskronans insida från kuspspetsen till cingulum, mellan mesial och distal lingual fossa. Den är ofta svagare på underkäkens hörntänder.', 'Eine Leiste auf der inneren Eckzahnkrone von der Höckerspitze zum Cingulum zwischen mesialer und distaler lingualer Fossa. Bei unteren Eckzähnen ist sie oft schwächer.', 'Una cresta en la cara interna del canino desde el vértice al cíngulo, entre las fosas linguales mesial y distal. Suele ser menos marcada en caninos inferiores.', 'Crista in superficie interna coronae canini ab apice cuspidis ad cingulum, inter fossas linguales mesialem et distalem. In caninis inferioribus saepe minus eminet.']);

const fos = [
  ['lingual-fossa', ['Lingual fossa', 'Lingual fossa', 'Linguale Fossa', 'Fosa lingual', 'Fossa lingualis'], ['A depression on the inner incisor crown between the incisal edge, marginal ridges and cingulum.', 'En fördjupning på incisivkronans insida mellan incisalkant, marginalåsar och cingulum.', 'Eine Vertiefung auf der inneren Inzisivenkrone zwischen Schneidekante, Randleisten und Cingulum.', 'Una depresión de la cara interna del incisivo entre borde incisal, crestas marginales y cíngulo.', 'Depressio superficiei internae coronae incisivi inter marginem incisalem, cristas marginales et cingulum.']],
  ['mesiolingual-fossa', ['Mesiolingual fossa', 'Mesiolingual fossa', 'Mesiolinguale Fossa', 'Fosa mesiolingual', 'Fossa mesiolingualis'], ['A depression on the mesial side of the canine lingual ridge, between that ridge and the mesial marginal ridge.', 'En fördjupning mesialt om hörntandens linguala ås, mellan denna och den mesiala marginalåsen.', 'Eine Vertiefung mesial der lingualen Eckzahnleiste zwischen dieser und der mesialen Randleiste.', 'Una depresión mesial a la cresta lingual del canino, entre esta y la cresta marginal mesial.', 'Depressio mesialis cristae lingualis canini, inter hanc et cristam marginalem mesialem.']],
  ['distolingual-fossa', ['Distolingual fossa', 'Distolingual fossa', 'Distolinguale Fossa', 'Fosa distolingual', 'Fossa distolingualis'], ['A depression on the distal side of the canine lingual ridge, bounded laterally by the distal marginal ridge.', 'En fördjupning distalt om hörntandens linguala ås, avgränsad åt sidan av den distala marginalåsen.', 'Eine Vertiefung distal der lingualen Eckzahnleiste, seitlich von der distalen Randleiste begrenzt.', 'Una depresión distal a la cresta lingual del canino, limitada lateralmente por la cresta marginal distal.', 'Depressio distalis cristae lingualis canini, lateraliter crista marginali distali terminata.']],
  ['central-fossa', ['Central fossa', 'Central fossa', 'Zentrale Fossa', 'Fosa central', 'Fossa centralis'], ['A depression near the center of a molar biting surface, surrounded by cusp slopes and intersecting developmental grooves.', 'En fördjupning nära molarens tugytecentrum, omgiven av kuspsluttningar och utvecklingsfåror som möts.', 'Eine Vertiefung nahe der Mitte der molaren Kaufläche, umgeben von Höckerabhängen und zusammenlaufenden Entwicklungsfurchen.', 'Una depresión cerca del centro de la superficie oclusal molar, rodeada de vertientes cuspídeas y surcos de desarrollo.', 'Depressio prope centrum superficiei occlusalis molaris, decliviis cuspidum et sulcis developmentalibus circumdata.']],
  ['mesial-fossa', ['Mesial fossa', 'Mesial fossa', 'Mesiale Fossa', 'Fosa mesial', 'Fossa mesialis'], ['A depression just inside the mesial marginal ridge of a premolar biting surface, near the mesial end of the groove system.', 'En fördjupning innanför premolarens mesiala marginalås, nära fårsystemets mesiala ände.', 'Eine Vertiefung innerhalb der mesialen Randleiste der Prämolarenkaufläche nahe dem mesialen Ende des Furchensystems.', 'Una depresión interna a la cresta marginal mesial del premolar, cerca del extremo mesial del sistema de surcos.', 'Depressio intra cristam marginalem mesialem premolaris, prope finem mesialem systematis sulcorum.']],
  ['distal-fossa', ['Distal fossa', 'Distal fossa', 'Distale Fossa', 'Fosa distal', 'Fossa distalis'], ['A depression inside the distal part of a posterior crown. On upper molars it lies distal to the oblique ridge; on premolars it is near the distal marginal ridge.', 'En fördjupning i den bakre kronans distala del. På överkäksmolarer ligger den distalt om den sneda åsen; på premolarer nära den distala marginalåsen.', 'Eine Vertiefung im distalen Teil einer Seitenzahnkrone. Bei oberen Molaren liegt sie distal der schrägen Leiste, bei Prämolaren nahe der distalen Randleiste.', 'Una depresión en la parte distal de una corona posterior. En molares superiores está distal a la cresta oblicua; en premolares cerca de la cresta marginal distal.', 'Depressio in parte distali coronae posterioris. In molaribus superioribus distaliter cristae obliquae, in premolaribus prope cristam marginalem distalem sita est.']],
] as [string, Translation, Translation][];
for (const [key, names, description] of fos) define(key, names, description);
for (const [side, words] of [['mesial', ['Mesial', 'Mesial', 'Mesiale', 'Mesial', 'mesialis']], ['distal', ['Distal', 'Distal', 'Distale', 'Distal', 'distalis']]] as const) {
  const names: Translation = [`${words[0]} marginal ridge`, `${words[1]} marginalås`, `${words[2]} Randleiste`, `Cresta marginal ${words[3].toLowerCase()}`, `Crista marginalis ${words[4]}`];
  define(`${side}-marginal-ridge`, names, side === 'mesial' ? ['The raised mesial border of a posterior biting surface or an anterior lingual surface. It bounds the adjacent fossa on the side nearer the dental midline.', 'Den upphöjda mesiala kanten på en bakre tuggyta eller främre lingualyta. Den avgränsar fossan på sidan närmare tandbågens mittlinje.', 'Der erhöhte mesiale Rand einer posterioren Kaufläche oder anterioren Lingualfläche. Er begrenzt die Fossa auf der zur Mittellinie gerichteten Seite.', 'El borde mesial elevado de una superficie oclusal posterior o lingual anterior. Limita la fosa por el lado más cercano a la línea media.', 'Margo mesialis elevatus superficiei occlusalis posterioris vel lingualis anterioris. Fossam in latere lineae medianae propiore terminat.'] : ['The raised distal border of a posterior biting surface or an anterior lingual surface. It bounds the adjacent fossa on the side farther from the dental midline.', 'Den upphöjda distala kanten på en bakre tuggyta eller främre lingualyta. Den avgränsar fossan på sidan längre från tandbågens mittlinje.', 'Der erhöhte distale Rand einer posterioren Kaufläche oder anterioren Lingualfläche. Er begrenzt die Fossa auf der von der Mittellinie abgewandten Seite.', 'El borde distal elevado de una superficie oclusal posterior o lingual anterior. Limita la fosa por el lado alejado de la línea media.', 'Margo distalis elevatus superficiei occlusalis posterioris vel lingualis anterioris. Fossam in latere a linea mediana remotiore terminat.']);
}
define('oblique-ridge', ['Oblique ridge', 'Sned ås', 'Schräge Leiste', 'Cresta oblicua', 'Crista obliqua'], ['A diagonal enamel ridge across an upper molar biting surface, linking the mesiolingual and distobuccal cusps. It separates central and distal fossae in this representative pattern.', 'En diagonal emaljås över överkäksmolarens tuggyta mellan mesiolingual och distobuckal kusp. Den skiljer central och distal fossa i detta exempel.', 'Eine diagonale Schmelzleiste auf der oberen Molarenkaufläche zwischen mesiolingualem und distobukkalem Höcker. Sie trennt zentrale und distale Fossa dieses Beispiels.', 'Una cresta diagonal de esmalte en la superficie oclusal molar superior entre las cúspides mesiolingual y distovestibular. Separa las fosas central y distal de este ejemplo.', 'Crista obliqua enameli in superficie occlusali molaris superioris cuspidem mesiolingualem distobuccali coniungit. Fossas centralem et distalem huius exempli separat.']);
define('transverse-ridge', ['Transverse ridge', 'Tvärgående ås', 'Querleiste', 'Cresta transversal', 'Crista transversa'], ['A ridge crossing between buccal and lingual cusps. In this mandibular first-premolar example it joins their triangular ridges and separates the mesial and distal fossae.', 'En ås mellan buckal och lingual kusp. I detta exempel av första underkäkspremolaren förenar den kusparnas triangulära åsar och skiljer mesial och distal fossa.', 'Eine Leiste zwischen bukkalem und lingualem Höcker. Bei diesem unteren ersten Prämolaren verbindet sie deren Dreiecksleisten und trennt mesiale und distale Fossa.', 'Una cresta entre las cúspides vestibular y lingual. En este primer premolar inferior une sus crestas triangulares y separa las fosas mesial y distal.', 'Crista inter cuspides buccalem et lingualem. In hoc premolari primo inferiore cristas triangulares iungit et fossas mesialem et distalem separat.']);
const grooves: [string, Translation, Translation][] = [
  ['central-groove', ['Central groove', 'Central fåra', 'Zentralfurche', 'Surco central', 'Sulcus centralis'], ['Runs through the inner biting surface between buccal and lingual/palatal cusp groups. Its length and branching depend on tooth type.', 'Löper genom tuggytans inre del mellan buckala och linguala/palatinala kuspar. Längd och förgrening beror på tandtyp.', 'Verläuft in der inneren Kaufläche zwischen bukkalen und lingualen/palatinalen Höckern. Länge und Verzweigung hängen vom Zahntyp ab.', 'Recorre la superficie oclusal interna entre cúspides vestibulares y linguales/palatinas. Su longitud y ramificación dependen del diente.', 'Per partem internam superficiei occlusalis inter cuspides buccales et linguales/palatinas transit. Longitudo et ramificatio a genere dentis pendent.']],
  ['buccal-groove', ['Buccal groove', 'Buckal fåra', 'Bukkale Furche', 'Surco vestibular', 'Sulcus buccalis'], ['Extends from the molar groove system towards the cheek-facing border, between the mesiobuccal and distobuccal cusps.', 'Löper från molarens fårsystem mot kindytans kant, mellan mesiobuckal och distobuckal kusp.', 'Zieht vom molaren Furchensystem zum wangenseitigen Rand zwischen mesiobukkalem und distobukkalem Höcker.', 'Se extiende desde los surcos molares hacia el borde vestibular entre las cúspides mesiovestibular y distovestibular.', 'A systemate sulcorum molaris ad marginem buccalem inter cuspides mesiobuccalem et distobuccalem tendit.']],
  ['lingual-groove', ['Lingual / palatal groove', 'Lingual / palatinal fåra', 'Linguale / palatinale Furche', 'Surco lingual / palatino', 'Sulcus lingualis / palatinus'], ['Extends towards the inner border of a molar biting surface, separating the mesiolingual and distolingual cusps in the illustrated pattern.', 'Löper mot molarens inre tugytekant mellan mesiolingual och distolingual kusp i det visade mönstret.', 'Zieht zum inneren Kauflächenrand des Molaren und trennt im dargestellten Muster mesiolingualen und distolingualen Höcker.', 'Se dirige al borde interno de la superficie oclusal molar y separa las cúspides mesiolingual y distolingual del patrón mostrado.', 'Ad marginem internum superficiei occlusalis molaris tendit et cuspides mesiolingualem et distolingualem exempli separat.']],
  ['distal-oblique-groove', ['Distal oblique groove', 'Distal sned fåra', 'Distale schräge Furche', 'Surco oblicuo distal', 'Sulcus obliquus distalis'], ['Runs diagonally through the distal fossa of an upper molar, distal to the oblique ridge, towards the lingual groove.', 'Löper diagonalt genom överkäksmolarens distala fossa, distalt om den sneda åsen, mot den linguala fåran.', 'Zieht diagonal durch die distale Fossa eines oberen Molaren, distal der schrägen Leiste, zur lingualen Furche.', 'Recorre diagonalmente la fosa distal del molar superior, distal a la cresta oblicua, hacia el surco lingual.', 'Oblique per fossam distalem molaris superioris, distaliter cristae obliquae, ad sulcum lingualem transit.']],
  ['distobuccal-groove', ['Distobuccal groove', 'Distobuckal fåra', 'Distobukkale Furche', 'Surco distovestibular', 'Sulcus distobuccalis'], ['Runs between the distobuccal and distal cusps of the mandibular first molar towards its buccal border.', 'Löper mellan distobuckal och distal kusp på första underkäksmolaren mot den buckala kanten.', 'Zieht zwischen distobukkalem und distalem Höcker des unteren ersten Molaren zum bukkalen Rand.', 'Discurre entre las cúspides distovestibular y distal del primer molar inferior hacia el borde vestibular.', 'Inter cuspides distobuccalem et distalem molaris primi inferioris ad marginem buccalem transit.']],
  ['mesiolingual-groove', ['Mesiolingual groove', 'Mesiolingual fåra', 'Mesiolinguale Furche', 'Surco mesiolingual', 'Sulcus mesiolingualis'], ['A groove near the mesial marginal ridge of the mandibular first premolar, extending towards the lingual surface beside its small lingual cusp.', 'En fåra nära första underkäkspremolarens mesiala marginalås, mot lingualytan intill den lilla linguala kuspen.', 'Eine Furche nahe der mesialen Randleiste des unteren ersten Prämolaren zur Lingualfläche neben dem kleinen lingualen Höcker.', 'Un surco próximo a la cresta marginal mesial del primer premolar inferior hacia la cara lingual junto a su pequeña cúspide lingual.', 'Sulcus prope cristam marginalem mesialem premolaris primi inferioris ad superficiem lingualem iuxta parvam cuspidem lingualem tendit.']],
];
for (const [key, names, description] of grooves) define(key, names, description);

define('labial-ridge', ['Labial ridge', 'Labial ås', 'Labiale Leiste', 'Cresta labial', 'Crista labialis'], ['A vertical convex ridge on the lip-facing canine crown, extending from the cusp region towards the cervical third. It marks the prominent middle developmental lobe; its relief varies between teeth.', 'En lodrät välvd ås på hörntandskronans läppsida, från kuspområdet mot den cervikala tredjedelen. Den markerar den framträdande mellersta utvecklingsloben; tydligheten varierar mellan tänder.', 'Eine vertikale Wölbung auf der lippenseitigen Eckzahnkrone vom Höckerbereich zum zervikalen Drittel. Sie kennzeichnet den mittleren Entwicklungslappen; ihre Ausprägung variiert.', 'Una cresta convexa vertical en la cara labial de la corona canina, desde la cúspide hacia el tercio cervical. Marca el lóbulo de desarrollo central prominente; su relieve varía.', 'Crista convexa verticalis in superficie labiali coronae canini, a regione cuspidis ad tertiam cervicalem extensa. Lobum evolutionis medium eminentem indicat; eminentia inter dentes variat.']);
define('buccal-ridge', ['Buccal ridge', 'Buckal ås', 'Bukkale Leiste', 'Cresta vestibular', 'Crista buccalis'], ['A convex ridge on the cheek-facing premolar crown, descending from the buccal cusp towards the cervical region between the neighboring developmental depressions. It is often more prominent on first than second premolars.', 'En välvd ås på premolarkronans kindyta, från den buckala kuspen mot cervikalområdet mellan närliggande utvecklingsfördjupningar. Den är ofta tydligare på första än andra premolaren.', 'Eine Wölbung auf der wangenseitigen Prämolarenkrone vom bukkalen Höcker zur zervikalen Region zwischen benachbarten Entwicklungsvertiefungen. Sie ist am ersten Prämolaren oft stärker ausgeprägt.', 'Una cresta convexa en la cara vestibular premolar, desde la cúspide vestibular hacia la región cervical entre depresiones de desarrollo vecinas. Suele ser más marcada en primeros premolares.', 'Crista convexa in superficie buccali coronae premolaris, a cuspide buccali ad regionem cervicalem inter depressiones evolutionis vicinas descendens. In premolaribus primis saepe eminentior est.']);

define('buccal-triangular-ridge', ['Buccal triangular ridge', 'Buckal triangulär ås', 'Bukkale Dreiecksleiste', 'Cresta triangular vestibular', 'Crista triangularis buccalis'], ['Descends from the buccal premolar cusp towards the central part of the biting surface. Its sloping sides border the mesial and distal fossae; the central groove may separate it from the lingual ridge.', 'Löper från premolarens buckala kusp mot tuggytans centrum. Dess sluttningar gränsar till mesiala och distala fossan; centralfåran kan skilja den från den linguala åsen.', 'Zieht vom bukkalen Prämolarenhöcker zur Kauflächenmitte. Ihre Flanken begrenzen die mesiale und distale Fossa; die Zentralfurche kann sie von der lingualen Leiste trennen.', 'Desciende de la cúspide vestibular del premolar hacia el centro oclusal. Sus vertientes limitan las fosas mesial y distal; el surco central puede separarla de la cresta lingual.', 'A cuspide buccali premolaris ad mediam superficiem occlusalem descendit. Latera fossas mesialem et distalem terminant; sulcus centralis eam a crista linguali separare potest.']);
define('lingual-triangular-ridge', ['Lingual / palatal triangular ridge', 'Lingual / palatinal triangulär ås', 'Linguale / palatinale Dreiecksleiste', 'Cresta triangular lingual / palatina', 'Crista triangularis lingualis / palatina'], ['Descends from the inner premolar cusp towards the central biting surface, opposite the buccal triangular ridge. Its size follows the lingual or palatal cusp and varies with premolar type.', 'Löper från premolarens inre kusp mot tuggytans centrum, mittemot den buckala triangulära åsen. Storleken följer den linguala eller palatinala kuspen och varierar med premolartyp.', 'Zieht vom inneren Prämolarenhöcker zur Kauflächenmitte gegenüber der bukkalen Dreiecksleiste. Ihre Größe entspricht dem lingualen oder palatinalen Höcker und variiert je nach Prämolartyp.', 'Desciende de la cúspide interna del premolar al centro oclusal, frente a la cresta triangular vestibular. Su tamaño depende de la cúspide lingual o palatina y del tipo de premolar.', 'A cuspide interna premolaris ad mediam superficiem occlusalem descendit, contra cristam triangularem buccalem. Magnitudo cuspidi linguali vel palatinae respondet et secundum genus premolaris variat.']);
define('mesial-marginal-groove', ['Mesial marginal groove', 'Mesial marginalfåra', 'Mesiale Randleistenfurche', 'Surco marginal mesial', 'Sulcus marginalis mesialis'], ['In this upper first premolar example, the developmental groove continues from the mesial end of the central groove across the mesial marginal ridge onto the proximal crown surface. Its extent varies between teeth.', 'I detta exempel av första överkäkspremolaren fortsätter utvecklingsfåran från centralfårans mesiala ände över den mesiala marginalåsen till kronans approximalyta. Utbredningen varierar mellan tänder.', 'In diesem Beispiel des oberen ersten Prämolaren setzt sich die Entwicklungsfurche vom mesialen Ende der Zentralfurche über die mesiale Randleiste auf die approximale Kronenfläche fort. Ihre Ausdehnung variiert.', 'En este ejemplo de primer premolar superior, el surco de desarrollo continúa desde el extremo mesial del surco central, cruza la cresta marginal mesial y llega a la cara proximal de la corona. Su extensión varía.', 'In hoc exemplo premolaris primi superioris sulcus evolutionis ab extremo mesiali sulci centralis trans cristam marginalem mesialem ad superficiem proximalem coronae transit. Extensio inter dentes variat.']);

export const SURFACE_FEATURE_KEYS = Object.keys(definitions);
export const featureNames = (key: string): Names => Object.fromEntries(LANGS.map((l, i) => [l, definitions[key].names[i]])) as Names;
export const SURFACE_SOURCES = [
  { title: 'US Air Force Dental Laboratory manual, chapter 4: Dental Tooth Anatomy', url: 'https://dentaltechnology.org/en/reference-library/air-force-dental-laboratory-manual/volume-1/chapter-04.md' },
  { title: 'The Permanent Maxillary and Mandibular Premolar Teeth', url: 'https://www.intechopen.com/chapters/62386' },
  { title: 'Dental Anatomy and Morphology of Permanent Teeth', url: 'https://www.intechopen.com/chapters/86255' },
  { title: 'Doctoropsy: Permanent Maxillary Canine', url: 'https://www.youtube.com/watch?v=rui02HbcEt8' },
];
export function surfaceFeatureContent(lang: Lang) {
  const i = LANGS.indexOf(lang);
  return Object.fromEntries(Object.entries(definitions).map(([key, d]) => [`surface-${key}`, { summary: d.description[i], sources: SURFACE_SOURCES, related: ['crown', 'enamel'] }]));
}
